import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import * as CyberIcons from 'cyber-icons-react'
import { colors } from 'cyber-icons-react'
import { DocumentPageSetup } from 'cyber-icons-react'


export default function Home() {
  const icons = Object.keys(CyberIcons);

  console.log('colors', colors)

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <div>
          <div>Select Theme</div>
          <div>
            {
              Object.keys(colors).map((color, index) => <div key={index}>
                <div>{color}</div>
                <div>
                  <CyberIcons.SystemLockScreen theme={color} />
                </div>
              </div>)
            }
          </div>
        </div>

        <div className="container-sections smallest">
          <section className="dark">
            {
              icons.map((s, i) => {
                if (typeof (CyberIcons as any)[s] !== 'function') {
                  return null;
                }
                const S = (CyberIcons as any)[s];
                return <S
                  key={i}
                  size={'1.5em'}
                  primary={'#de004e'}
                  secondary={'#321450'}
                  border={'#f887ff'}


                />
              })
            }
          </section>
        </div>
        <div className="container-sections">
          <section className="dark">
            {
              icons.map((s, i) => {
                if (typeof (CyberIcons as any)[s] !== 'function') {
                  return null;
                }
                const S = (CyberIcons as any)[s];
                return <S
                  key={i}
                  size={'2em'}
                />
              })
            }
          </section>
          <section className="dark">
            {
              icons.map((s, i) => {
                if (typeof (CyberIcons as any)[s] !== 'function') {
                  return null;
                }
                const S = (CyberIcons as any)[s];
                return <S
                  key={i}
                  size={'3em'}
                  primary={'#024059'}
                  secondary={'#980BBF'}
                  border={'#F2E307'}
                />
              })
            }
          </section>
          <section className="dark">
            {
              icons.map((s, i) => {
                if (typeof (CyberIcons as any)[s] !== 'function') {
                  return null;
                }
                const S = (CyberIcons as any)[s];
                return <S
                  key={i}
                  size={'3em'}
                  primary={'magenta'}
                  secondary={'blue'}
                  border={'cyan'}
                />
              })
            }
          </section>
          <section className="dark">
            {
              icons.map((s, i) => {
                if (typeof (CyberIcons as any)[s] !== 'function') {
                  return null;
                }
                const S = (CyberIcons as any)[s];
                return <S
                  key={i}
                  size={'3em'}
                  primary={'white'}
                  secondary={'white'}
                  border={'blue'}
                />
              })
            }
          </section>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
